color: null
fieldLayouts:
  25cd55e6-6d41-4c25-b2b2-788ba58fb7b1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T13:18:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Building
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 48759240-210f-468c-9d16-6cd2541d44e0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T15:41:38+00:00'
            elementCondition: null
            fieldUid: 8b2381b3-1e31-4f3f-b9fe-67d5e5f66df3 # Departments
            handle: null
            includeInCards: false
            instructions: null
            label: 'Departments Within'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebfaa9a3-ea0a-4c37-a9d2-ab4255d8df6c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5e87e6d-72ce-4b6c-83fe-fd6d8a3fd425
        userCondition: null
handle: ent_buildings
hasTitleField: true
icon: building
name: Buildings
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
