color: null
fieldLayouts:
  b45db72f-20f9-455a-8c55-2c5de193c37e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-31T10:08:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Item
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a8309203-7a9a-4b7d-b299-705a87a4a0a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-31T13:50:35+00:00'
            elementCondition: null
            fieldUid: 8a0991bc-a55b-423f-be98-b0b07f622009 # Job Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afbfbf2b-c43c-4335-ac9c-ee90c74f7104
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 388ae568-03f6-4871-8ba6-2724cf525594
        userCondition: null
handle: ent_transfusion
hasTitleField: true
icon: droplet
name: Transfusion
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
