color: null
fieldLayouts:
  d345630f-fc1b-44e0-9ab5-8f4a1d10a896:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T13:28:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Job Option'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23a7aa71-2557-4457-83b5-00cb47605f37
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-03-27T15:57:10+00:00'
            elementCondition: null
            fieldUid: dd26ef8a-39c6-4323-8d51-c0bb6a57f95d # Plain
            handle: fd_shortened
            includeInCards: false
            instructions: null
            label: Shortened
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c646d818-bb40-468b-9574-9701a5779fff
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: f41710d6-4de6-4d99-b27d-6e90950bb334
        userCondition: null
handle: ent_jobOptions
hasTitleField: true
icon: filter
name: 'Job Options'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
