color: null
fieldLayouts:
  d0d9dd94-3bfb-419c-a1a8-183af97759be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T16:08:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Sample Type'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8d03f861-ecfa-493f-88a9-105f768f51b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-31T13:30:46+00:00'
            elementCondition: null
            fieldUid: 8a0991bc-a55b-423f-be98-b0b07f622009 # Job Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50e73665-231a-483e-a90a-a793fbba48a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b455db3b-2db5-4a0e-9134-699ba7f9fe3c
        userCondition: null
handle: ent_samples
hasTitleField: true
icon: vial
name: Samples
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
