color: null
fieldLayouts:
  c7f90ba0-1a43-426d-8729-924a9f94bbf9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T13:19:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Department
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 054f6829-baf5-4d38-bb5e-cb24d0aab4c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b9934a6d-39e9-4d5b-bc1f-08aff1effb0a
        userCondition: null
handle: ent_departments
hasTitleField: true
icon: cabinet-filing
name: Departments
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
