color: null
fieldLayouts:
  978cd55e-adf1-485a-9c10-d95999358ef8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T16:11:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Transport Option'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6d8a51f0-abf3-45ba-b784-651f3362e92f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40e7b750-5fd4-4214-bf90-b037f088f35f
        userCondition: null
handle: ent_transportOptions
hasTitleField: true
icon: stretcher
name: 'Transport Options'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
