color: null
fieldLayouts:
  5e156e07-03e9-4007-8548-91dc49088be7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-31T13:42:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Item
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 34a3121e-4c5f-4423-bea7-7d7ab72c1ae3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-31T13:43:51+00:00'
            elementCondition: null
            fieldUid: 8a0991bc-a55b-423f-be98-b0b07f622009 # Job Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6035c0da-43c6-49a7-a487-d939e9cd84a2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d948680e-1833-4d20-ba8a-1e93bf72a396
        userCondition: null
handle: ent_NEWadHoc
hasTitleField: true
icon: null
name: Ad-Hoc
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
