color: null
fieldLayouts:
  f5c01a58-5cb2-422e-a942-f742027e0153:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T13:21:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Job Category'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 383f6918-20fe-426b-9f50-faa0c9b66f87
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 99e7b8c8-4f29-4262-8f46-3b423be9cf8a
        userCondition: null
handle: ent_jobCategories
hasTitleField: true
icon: null
name: 'Job Categories'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
