color: null
fieldLayouts:
  f6e62a36-2f6a-4417-a633-f77a00f00cb0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-28T07:46:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Type
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7cb92348-5720-4dd4-87ac-08b2bca15039
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bc01e47b-9094-45db-bb2a-4c402327c126
        userCondition: null
handle: gases
hasTitleField: true
icon: prescription-bottle
name: Gases
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
