color: null
fieldLayouts:
  b981b764-549d-415e-b341-7b1f432cf11f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-28T08:56:59+00:00'
            elementCondition: null
            fieldUid: 93fb37a4-7aca-4863-9d25-45cdcad333bc # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73392dcf-e29f-4a56-bcfd-4b299b96a493
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-03-28T08:56:59+00:00'
            elementCondition: null
            fieldUid: abbb0b4f-f27c-4f20-986d-302a3ae63dd8 # Shift Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59250334-982c-4ad3-91a4-cad5aaf0ba24
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: a7c280ff-040d-4a18-9ca1-47008ffb3e8d
        userCondition: null
handle: shifts
hasTitleField: false
icon: calendar-days
name: Shifts
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{fd_shiftType.label} - {now|date(''d/m/Y'')}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
