columnSuffix: null
handle: fd_itemType
instructions: null
name: 'Item Type'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:4c6101fb-6e77-4868-b50e-46525b0fd4d0' # General Items
    - 'section:6986b576-80c3-4533-87d5-099d591c53cb' # Gases
    - 'section:f50e7600-0a56-4e2b-84e9-446a4a5866c3' # Pathology
    - 'section:6833053b-93f2-4a3b-8af9-c2cc5ef8ef6a' # Samples
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
