columnSuffix: null
handle: fd_notes
instructions: null
name: Notes
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 5
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
