columnSuffix: null
handle: fd_shiftType
instructions: null
name: 'Shift Type'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Day
        -
          - value
          - day
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Night
        -
          - value
          - night
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
