dateModified: 1743430048
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Structures
      type: heading
    -
      key: 'section:7ba4adac-0649-4224-bdc2-faf8f232fd2c' # Job Categories
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:8af449d1-d16b-4c5a-a1e4-772372ee9e54' # Staff
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Estates
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:976976ab-4f00-428a-af50-4320ea84c47b' # Buildings
      tableAttributes:
        - 'field:8b2381b3-1e31-4f3f-b9fe-67d5e5f66df3' # Departments
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:69dd0b22-fdad-4a5d-9258-296dbac737a5' # Departments
      tableAttributes:
        - 'fieldInstance:9bf6cc7f-493c-4c91-9520-9924561dd34c'
      type: native
    -
      heading: 'Items and Assets'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:4c6101fb-6e77-4868-b50e-46525b0fd4d0' # Ad-Hoc
      tableAttributes:
        - 'field:8a0991bc-a55b-423f-be98-b0b07f622009' # Job Category
        - status
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:6833053b-93f2-4a3b-8af9-c2cc5ef8ef6a' # Samples
      tableAttributes:
        - 'field:8a0991bc-a55b-423f-be98-b0b07f622009' # Job Category
        - status
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:6986b576-80c3-4533-87d5-099d591c53cb' # Gases
      tableAttributes:
        - 'field:8a0991bc-a55b-423f-be98-b0b07f622009' # Job Category
        - status
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:7d0d7bb1-86b9-4f2b-84d8-f5a2fc42eb4e' # Assets
      tableAttributes:
        - 'field:8a0991bc-a55b-423f-be98-b0b07f622009' # Job Category
        - status
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:9f7b0f90-d4b6-445d-9da6-c5efa0ef564b' # Transfusion
      tableAttributes:
        - 'field:8a0991bc-a55b-423f-be98-b0b07f622009' # Job Category
        - status
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:1f97b433-8801-4979-a2fe-aeaac36fe939' # Transfer Type
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: ''
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:365108a7-63e3-43fd-bb1b-5b1e0979d51e' # Shifts
      tableAttributes:
        - status
      type: native
    -
      heading: ''
      type: heading
    -
      heading: ''
      type: heading
    -
      key: 'section:09bb9322-30d5-4e58-aa25-6bf9d921a011'
      type: native
email:
  fromEmail: access@hypha.media
  fromName: 'Porter Track'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1f97b433-8801-4979-a2fe-aeaac36fe939: 'Transfer Type' # Transfer Type
    3e98e49d-374c-46d3-b44d-b816a22d798b: Buildings # Buildings
    4c6101fb-6e77-4868-b50e-46525b0fd4d0: Ad-Hoc # Ad-Hoc
    6c4cb69d-ed30-4378-a9dc-cbad05892ca7: Samples # Samples
    7ba4adac-0649-4224-bdc2-faf8f232fd2c: 'Job Categories' # Job Categories
    7d0d7bb1-86b9-4f2b-84d8-f5a2fc42eb4e: Assets # Assets
    8a0991bc-a55b-423f-be98-b0b07f622009: 'Job Category' # Job Category
    8af449d1-d16b-4c5a-a1e4-772372ee9e54: Staff # Staff
    8b2381b3-1e31-4f3f-b9fe-67d5e5f66df3: Departments # Departments
    9f7b0f90-d4b6-445d-9da6-c5efa0ef564b: Transfusion # Transfusion
    19fc0c90-a6ff-406c-969a-1845da802de0: Staff # Staff
    024e7ea3-9daf-4039-a7d9-f128c7efa662: Gases # Gases
    29b2392c-1769-4679-be79-9597e31b86ab: Assets # Assets
    39e1a7a3-c7f1-49b6-b4a7-a5f8b7e36e46: Ad-Hoc # Ad-Hoc
    61cd436b-67c4-45ff-b404-9d5f0b6e380f: 'Job Options' # Job Options
    066b15d3-420c-47dc-8971-7f87fbfafde1: 'Transport Options' # Transport Options
    69dd0b22-fdad-4a5d-9258-296dbac737a5: Departments # Departments
    93fb37a4-7aca-4863-9d25-45cdcad333bc: Date # Date
    898bdf25-045f-4472-809a-93b4b6f25470: Transfusion # Transfusion
    6377b2a4-4b9a-4d81-a7d6-48c3c6d0c850: Shifts # Shifts
    6986b576-80c3-4533-87d5-099d591c53cb: Gases # Gases
    30567af9-d3c8-4734-84f2-9cbece3ab7d2: Departments # Departments
    234179bc-9833-430f-b5d1-5328981b44b1: 'Job Categories' # Job Categories
    365108a7-63e3-43fd-bb1b-5b1e0979d51e: Shifts # Shifts
    976976ab-4f00-428a-af50-4320ea84c47b: Buildings # Buildings
    6833053b-93f2-4a3b-8af9-c2cc5ef8ef6a: Samples # Samples
    a8c08db8-6502-4930-a808-9da8335199bf: 'Porter Track' # Porter Track
    abbb0b4f-f27c-4f20-986d-302a3ae63dd8: 'Shift Type' # Shift Type
    d6094da4-5bef-4dce-b2bb-83ea84ec2d30: 'Porter Track' # Porter Track
    dd26ef8a-39c6-4323-8d51-c0bb6a57f95d: Plain # Plain
system:
  edition: solo
  live: true
  name: 'Porter Track'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
