dateModified: 1742988728
email:
  fromEmail: access@hypha.media
  fromName: 'Porter Track'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    a8c08db8-6502-4930-a808-9da8335199bf: 'Porter Track' # Porter Track
    d6094da4-5bef-4dce-b2bb-83ea84ec2d30: 'Porter Track' # Porter Track
system:
  edition: solo
  live: true
  name: 'Porter Track'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
