dateModified: 1743091312
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      heading: Structures
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:976976ab-4f00-428a-af50-4320ea84c47b' # Buildings
      tableAttributes:
        - 'field:8b2381b3-1e31-4f3f-b9fe-67d5e5f66df3' # Departments
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:69dd0b22-fdad-4a5d-9258-296dbac737a5' # Departments
      tableAttributes:
        - 'fieldInstance:9bf6cc7f-493c-4c91-9520-9924561dd34c'
      type: native
    -
      key: 'section:7ba4adac-0649-4224-bdc2-faf8f232fd2c' # Job Categories
      type: native
    -
      key: 'section:4c6101fb-6e77-4868-b50e-46525b0fd4d0' # Job Options
      type: native
    -
      key: 'section:272699c6-9270-4b86-95e8-0c22f1378c21' # Job Types
      type: native
    -
      key: 'section:8af449d1-d16b-4c5a-a1e4-772372ee9e54' # Staff
      type: native
    -
      key: 'section:97e0ccb9-edab-47da-b914-08e25c5271f0' # Tasks
      type: native
email:
  fromEmail: access@hypha.media
  fromName: 'Porter Track'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0d29dd76-d6c5-4fc1-94e2-2ba179722665: 'Job Types' # Job Types
    01b0afb7-da30-4504-b311-b07bbdaccf74: 'Item Type' # Item Type
    3c114211-5a65-4997-84f4-be167e9fa220: 'Job Category' # Job Category
    3e98e49d-374c-46d3-b44d-b816a22d798b: Buildings # Buildings
    4c6101fb-6e77-4868-b50e-46525b0fd4d0: 'Job Options' # Job Options
    7ba4adac-0649-4224-bdc2-faf8f232fd2c: 'Job Categories' # Job Categories
    8af449d1-d16b-4c5a-a1e4-772372ee9e54: Staff # Staff
    8b2381b3-1e31-4f3f-b9fe-67d5e5f66df3: Departments # Departments
    19fc0c90-a6ff-406c-969a-1845da802de0: Staff # Staff
    26e258b1-8cb4-4f3c-a49e-5a3bd1f771cc: Dropdown # Dropdown
    61cd436b-67c4-45ff-b404-9d5f0b6e380f: 'Job Options' # Job Options
    66e17ffb-bfb7-44e4-b712-f1ad5fd2e000: 'Transport Type' # Transport Type
    69dd0b22-fdad-4a5d-9258-296dbac737a5: Departments # Departments
    087e3991-f336-4d75-ba5d-7ee9b67d991c: Building # Building
    93fb37a4-7aca-4863-9d25-45cdcad333bc: Date # Date
    97e0ccb9-edab-47da-b914-08e25c5271f0: Tasks # Tasks
    552a4505-21bc-4931-8169-456df83a265b: Tasks # Tasks
    1433d618-7471-4baf-97ab-0f99412d4937: Time # Time
    9125c8fc-42f2-4111-80eb-7f45937c21ac: 'Task Options' # Task Options
    30567af9-d3c8-4734-84f2-9cbece3ab7d2: Departments # Departments
    234179bc-9833-430f-b5d1-5328981b44b1: 'Job Categories' # Job Categories
    272699c6-9270-4b86-95e8-0c22f1378c21: 'Job Types' # Job Types
    976976ab-4f00-428a-af50-4320ea84c47b: Buildings # Buildings
    a8c08db8-6502-4930-a808-9da8335199bf: 'Porter Track' # Porter Track
    b4a6b8df-f8b3-4d4b-8baf-419b69270987: 'Staff Member' # Staff Member
    bd564c60-b3e7-4a06-8b3c-2efe4dce18f3: 'To Department' # To Department
    d6094da4-5bef-4dce-b2bb-83ea84ec2d30: 'Porter Track' # Porter Track
    dd26ef8a-39c6-4323-8d51-c0bb6a57f95d: Plain # Plain
    e46fd863-907c-44f3-a745-dd0b4fa995a8: Notes # Notes
    f9aad2b1-7e69-481b-8b97-3ce60fcdd0db: 'From Department' # From Department
system:
  edition: solo
  live: true
  name: 'Porter Track'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
