defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 29b2392c-1769-4679-be79-9597e31b86ab # Assets
handle: assets
maxAuthors: 1
name: Assets
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: assets/_entry.twig
    uriFormat: 'assets/{slug}'
structure:
  maxLevels: 1
  uid: cef5d341-b4ca-4d5e-b5b4-64496be5c3df
type: structure
