defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 024e7ea3-9daf-4039-a7d9-f128c7efa662 # Gases
handle: gases
maxAuthors: 1
name: Gases
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: oxygen/_entry.twig
    uriFormat: 'oxygen/{slug}'
structure:
  maxLevels: 1
  uid: fa0b4cb8-cd61-4d08-ac18-f652fcd34916
type: structure
