defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: ent_itemsAndAssets
    name: 'Items and Assets'
    uid: 61cd436b-67c4-45ff-b404-9d5f0b6e380f # Job Options
handle: generalItems
maxAuthors: 1
name: 'General Items'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: general-items/_entry.twig
    uriFormat: 'general-items/{slug}'
structure:
  maxLevels: 1
  uid: ec3e39b8-68ae-452e-9107-59227a19fd73
type: structure
