defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 234179bc-9833-430f-b5d1-5328981b44b1 # Job Categories
handle: jobCategories
maxAuthors: 1
name: 'Job Categories'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: job-categories/_entry.twig
    uriFormat: 'job-categories/{slug}'
structure:
  maxLevels: 1
  uid: 244cd928-08c3-4d2b-97bb-b61ee2dab757
type: structure
