defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d9f5253d-630f-41f4-9552-78b4c22c4a48 # Pathology
handle: pathology
maxAuthors: 1
name: Pathology
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: pathology/_entry.twig
    uriFormat: 'pathology/{slug}'
structure:
  maxLevels: 1
  uid: 99a125b4-7064-4adb-bddb-6589e32b8a54
type: structure
