defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6c4cb69d-ed30-4378-a9dc-cbad05892ca7 # Samples
handle: samples
maxAuthors: 1
name: Samples
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: samples/_entry.twig
    uriFormat: 'samples/{slug}'
structure:
  maxLevels: 1
  uid: 3bfd1244-c2cd-4fc1-a5cc-aaf0c0ba37e7
type: structure
