defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6377b2a4-4b9a-4d81-a7d6-48c3c6d0c850 # Shifts
handle: shifts
maxAuthors: 1
name: Shifts
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: shifts/_entry.twig
    uriFormat: 'shifts/{slug}'
type: channel
