defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 898bdf25-045f-4472-809a-93b4b6f25470 # Transfusion
handle: transfusion
maxAuthors: 1
name: Transfusion
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: transfusion/_entry.twig
    uriFormat: 'transfusion/{slug}'
structure:
  maxLevels: 1
  uid: a15300c8-53ad-44ca-ac8c-2820888d8e00
type: structure
