defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 066b15d3-420c-47dc-8971-7f87fbfafde1 # Transport Options
handle: transferType
maxAuthors: 1
name: 'Transfer Type'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a8c08db8-6502-4930-a808-9da8335199bf: # Porter Track
    enabledByDefault: true
    hasUrls: true
    template: transport-options/_entry.twig
    uriFormat: 'transport-options/{slug}'
structure:
  maxLevels: 2
  uid: 3d3c44d4-8d95-4372-a095-cf8527ec8872
type: structure
